name: porydrive
base: core20
version: '1.0'
summary: A simple 3D driving game.
description: |
  A simple 3D driving game, you have to catch the Porygon.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
    run-on: amd64
  - build-on: arm64
    run-on: arm64
  - build-on: armhf
    run-on: armhf

apps:
  porydrive:
    extensions: [gnome-3-38]
    command: porydrive
    plugs:
    - desktop
    - desktop-legacy
    - gsettings
    - opengl
    - wayland
    - x11

parts:
  porydrive:
    source: https://github.com/mrbid/porydrive
    source-type: git
    plugin: make
    build-packages:
    - libglfw3-dev
    stage-packages:
    - libglfw3
    - libgles2
