name: porydrive
base: core20
version: '1.6'
summary: A simple 3D driving game.
description: |
  A simple 3D driving game, you have to catch the Porygon. Drive around and "collect" Porygon, each time you collect a Porygon a new one will randomly spawn somewhere on the map. A Porygon colliding with a purple cube will cause it to light up blue, this can help you find them. Upon right clicking the mouse you will switch between Ariel and Close views, in the Ariel view it is easier to see which of the purple cubes that the Porygon is colliding with.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
    run-on: amd64
  - build-on: arm64
    run-on: arm64
  - build-on: armhf
    run-on: armhf

apps:
  porydrive:
    extensions: [gnome-3-38]
    command: porydrive
    plugs:
    - desktop
    - desktop-legacy
    - gsettings
    - opengl
    - wayland
    - x11

parts:
  porydrive:
    source: https://github.com/mrbid/porydrive
    source-type: git
    plugin: make
    build-packages:
    - libglfw3-dev
    stage-packages:
    - libglfw3
    - libgles2
